### ISSUE TITLE
Create Footer for the website

### ISSUE THREAD

**Issue by this-is-aishwarya** [Prasang023/MERN-ecommerce-website#6]
Add footer to add:
- Contact information
- Details about the e-commerce company
- Social media posts or links, or even to discover new or related content on the site.

Adding a footer will provide an attractive appeal to the website

Please assign me the issue.

**Comment by Prasang023** [comment]
Sure

**Comment by singhkaran202** [comment]
Hello @Prasang023, I'd love to work on it, if that's OK.
Could you please assign me this issue?

**Comment by Prasang023** [comment]
Sorry @singhkaran202, but this issue is already assigned to @this-is-aishwarya. You may create other issues in this repo and work on them.
